version: "3.2"

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=task
    volumes:
      - cqrs_data_mysql:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  cqrs_data_mysql: