spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&rewriteBatchedStatements=true
    username: root
    password: rootpasswd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


axon:
  serializer:
    events: jackson
  amqp:
    exchange: task-exchange
  eventhandling:
    processors:
      storage:
        source: myQueueMessageSource